// Bounded package trust boundary: OPC names, content types, relationships
// (document-engine tasks 2.2, 2.6).
export {
  type NameRejection,
  type NameResult,
  normalizePartName,
  partNameKey,
  asciiFold,
  detectDuplicateNames,
  resolveInternalTarget,
  validateExternalTarget,
} from './opc-names.js';
export {
  type DefaultRecord,
  type OverrideRecord,
  type ContentTypeRecords,
  type ContentTypeError,
  type ContentTypeIndex,
  type IndexResult,
  type ResolveResult,
  isValidMime,
  extensionKey,
  buildContentTypeIndex,
  resolveContentType,
} from './content-types.js';
export {
  type TargetMode,
  type RelationshipRecord,
  type RelationshipError,
  type RelationshipSetResult,
  type ResolvedRelationship,
  type ImageRelationshipResolution,
  IMAGE_RELATIONSHIP_TYPE,
  buildRelationshipSet,
  resolveRelationship,
  resolveImageRelationship,
} from './relationships.js';
export {
  DANGEROUS_KEYS,
  DangerousKeyError,
  isDangerousKey,
  nullRecord,
  toSafeRecord,
} from './safe-record.js';
export {
  type XmlNode,
  type XmlRejection,
  type XmlResult,
  type XmlLimits,
  readXml,
  findElement,
  childElements,
  textContent,
} from './xml-reader.js';
export {
  WML_NAMESPACE_URI,
  XML_NAMESPACE_URI,
  XMLNS_NAMESPACE_URI,
  type OoxmlNodeId,
  type OoxmlNamespaceBinding,
  type OoxmlAttribute,
  type OoxmlXmlSpaceAttribute,
  type OoxmlWmlValAttribute,
  type OoxmlGenericExtensionAttribute,
  type OoxmlKnownNodeAttribute,
  type OoxmlDocumentNode,
  type OoxmlBodyNode,
  type OoxmlParagraphNode,
  type OoxmlRunNode,
  type OoxmlRunPropertiesNode,
  type OoxmlTextElementNode,
  type OoxmlParagraphPropertiesNode,
  type OoxmlTabNode,
  type OoxmlHardBreakNode,
  type OoxmlHyperlinkNode,
  type OoxmlBookmarkStartNode,
  type OoxmlBookmarkEndNode,
  type OoxmlFldCharNode,
  type OoxmlInstrTextNode,
  type OoxmlFldSimpleNode,
  type OoxmlFootnotesNode,
  type OoxmlEndnotesNode,
  type OoxmlNoteNode,
  type OoxmlNoteReferenceNode,
  type OoxmlNoteRefNode,
  type OoxmlSeparatorNode,
  type OoxmlContinuationSeparatorNode,
  type OoxmlContentControlNode,
  type OoxmlContentControlPropertiesNode,
  type OoxmlContentControlEndPropertiesNode,
  type OoxmlContentControlContentNode,
  type OoxmlContentControlDropDownListNode,
  type OoxmlContentControlComboBoxNode,
  type OoxmlContentControlListItemNode,
  type OoxmlContentControlDateNode,
  type OoxmlContentControlDateFormatNode,
  type OoxmlContentControlLidNode,
  type OoxmlContentControlStoreMappedDataAsNode,
  type OoxmlContentControlCalendarNode,
  type OoxmlContentControlTextNode,
  type OoxmlContentControlDataBindingNode,
  type OoxmlContentControlCheckboxNode,
  type OoxmlContentControlCheckedNode,
  type OoxmlContentControlCheckedStateNode,
  type OoxmlContentControlUncheckedStateNode,
  type OoxmlGenericElementNode,
  type OoxmlTextNode,
  type OoxmlElement,
  type OoxmlNode,
  type OoxmlPart,
  type OoxmlPartMetadata,
  type OoxmlReadRejection,
  type OoxmlReadResult,
  type OoxmlNodeIdentityRules,
  type OoxmlInvariantIssueCode,
  type OoxmlInvariantIssue,
  type OoxmlInvariantResult,
  OOXML_NODE_IDENTITY_RULES,
  readOoxmlPart,
  validateOoxmlPart,
  serializeOoxmlPart,
  canonicalOoxmlFingerprint,
  ooxmlTreesEqual,
} from './ooxml-tree.js';
export { readOnOffChild, isContentRevisionKind, isRangeMarkerKind } from './ooxml-shared.js';
export {
  relationshipsOf,
  relsPartNameFor,
  resolveContentTypeOf,
  contentTypesPartBytes,
  validatePackageInvariants,
  withContentTypeOverride,
  withNewPart,
  withRelationship,
  type PackageInvariantCode,
  type PackageInvariantIssue,
  type PackageInvariantResult,
} from './package-edit.js';
export {
  allocateDrawingPropertyId,
  withBinaryPart,
  withEmbeddedImage,
  withoutUnreferencedImagePart,
  type DrawingPropertyIdResult,
} from './drawing-package-edit.js';
export {
  type ZipRejection,
  type ZipLimits,
  type ZipReadResult,
  DEFAULT_ZIP_LIMITS,
  readZip,
  writeZip,
} from './zip.js';
export { isValidNCName, isValidQName, assertValidQName, PrefixAllocator } from './qname.js';
export {
  type HrefProjection,
  type InertExecutableKind,
  type ContentItem,
  type ScrubResult,
  sanitizeHref,
  escapeXml,
  escapeCssString,
  containsCssFetch,
  INERT_EXECUTABLE_KINDS,
  isInertExecutable,
  isEvaluableField,
  scrubExport,
} from './sinks.js';
export {
  readOoxmlPackage,
  writeOoxmlPackage,
  withPart,
  DEFAULT_OOXML_PACKAGE_LIMITS,
  type OoxmlPackage,
  type OoxmlPackageLimits,
  type OoxmlPackageRejection,
  type OoxmlPackageResult,
  type OoxmlExternalTarget,
} from './ooxml-package.js';
export {
  type SupportedImageMime,
  type PreservedImageMime,
  type ImageResourceState,
  type ImageDecodePort,
  type ImageResourceLookup,
  type CreateImageResourceCacheOptions,
  createImageResourceCache,
  imageResourceLookupFor,
  liveDrawingReferenceCount,
  sniffImageMime,
  hasBoundedSvgRoot,
  MAX_SVG_SNIFF_BYTES,
  validatePngHeader,
  validateGifHeader,
  validateJpegHeader,
  validateRasterHeader,
  type ValidatedRasterHeader,
} from './image-resources.js';
export {
  resolveHeaderFooterParts,
  resolveHeaderFooterPartsBySection,
  resolveHeaderFooterResolutionBySection,
  collectSectionPropertyNodes,
  type HeaderFooterKind,
  type HeaderFooterParts,
  type HeaderFooterSectionResolution,
  type HeaderFooterSlotMeta,
  type HeaderFooterVariant,
} from './hf-references.js';
export {
  deobfuscateFont,
  readEmbeddedFonts,
  type EmbeddedFont,
  type FontStyleKey,
  type ReadEmbeddedFontsOptions,
} from './embedded-fonts.js';
export {
  applyEdits,
  collectNodeIds,
  createNodeIdAllocator,
  findNode,
  hasNode,
  insertChildren,
  parentNodeOf,
  removeNode,
  replaceChildren,
  replaceNode,
  type EditOptions,
  type OoxmlEditResult,
} from './ooxml-edit.js';
export {
  PAGE_BREAK_CHAR,
  hardBreakAttributes,
  hardBreakKind,
  hardBreakText,
  isPageBreakNode,
  type HardBreakKind,
} from './hard-break.js';
export {
  FIELD_ATOM_CHAR,
  atomicFieldSpansOf,
  fieldAtomText,
  fieldOnOffAttribute,
  fldCharType,
  fldSimpleInstr,
  hasLegacyFormFieldData,
  instrTextValue,
  isFieldChrome,
  isFldChar,
  isFldCharNode,
  isFldSimple,
  isFldSimpleNode,
  isInstrText,
  isInstrTextNode,
  isLegalFldCharType,
  type AtomicFieldSpan,
  type FldCharType,
} from './field-nodes.js';
export {
  TOC_MAX_BOOKMARKS_PER_REFRESH,
  TOC_MAX_ENTRIES,
  TOC_MAX_FIELD_NESTING,
  TOC_MAX_INSTRUCTION_CHARS,
  TOC_MAX_PAGE_PASSES,
  parseTocInstruction,
  type TocInstruction,
} from './toc-instruction.js';
export { detectBodyTocs, findDetectedToc, type DetectedToc } from './toc-detect.js';
export {
  bookmarkPairNodes,
  buildTocContentControl,
  buildTocEntryParagraph,
  planTocEntries,
  TOC_LEVEL_INDENT_TWIPS,
  tocEntryText,
  tocLeftIndentTwips,
  type TocEntryPlan,
  type TocOutlineHeading,
} from './toc-build.js';
export { resolveTocRowHeadings } from './toc-rows.js';
export {
  deriveOoxmlIndexes,
  indexStyles,
  stylesPartOf,
  type OoxmlIndexes,
  type ParagraphIndexEntry,
  type StoryIndexEntry,
  type StyleIndexEntry,
} from './ooxml-indexes.js';
export {
  digestPart,
  diffSemanticDigests,
  semanticDigest,
  type DigestDifference,
  type ParagraphDigest,
  type SemanticDigest,
  type StoryDigest,
} from './ooxml-digest.js';
export {
  isValidParaId,
  fnv1a32,
  mintParaId,
  mintedParagraphIdentityAttributes,
  normalizeParagraphIdentity,
  paraIdOf,
  usedParaIds,
  w14RootPrefix,
} from './para-id.js';
export { ensureListDefinition, ensureNumberingLevel, type ListKind } from './numbering-part.js';
export { buildBookmarkIndex, type BookmarkAnchor, type BookmarkIndex } from './bookmarks.js';
export {
  collectFlowBlocks,
  contentControlContentOf,
  isContentControl,
  isContentControlContent,
  walkAllStoryParagraphs,
  walkParagraphInline,
  walkStoryBlocks,
} from './content-control-walk.js';
export {
  authorableHyperlinkTarget,
  ensureHyperlinkRelationship,
  relationshipTargetIn,
  type EnsuredHyperlinkRelationship,
} from './hyperlink-part.js';
export {
  HYPERLINK_RELATIONSHIP_TYPE,
  OFFICE_RELATIONSHIP_NAMESPACE_URI,
  hyperlinkAnchorOf,
  hyperlinkRelationshipIdOf,
  hyperlinkTargetOf,
  isHyperlinkNode,
  type HyperlinkKind,
  type HyperlinkTarget,
  type RelationshipTargetResolver,
} from './hyperlink.js';
export {
  applyHeaderFooterLifecycleOp,
  isHeaderFooterLifecycleOp,
  type HeaderFooterLifecycleImpact,
  type HeaderFooterLifecycleOp,
  type HeaderFooterLifecycleRejection,
  type HeaderFooterLifecycleResult,
} from './hf-lifecycle.js';
export {
  NOTE_ATOM_CHAR,
  NOTE_CONTINUATION_SEPARATOR_ID,
  NOTE_ID_MAX,
  NOTE_ID_MIN,
  NOTE_SEPARATOR_ID,
  MAX_NOTES_PER_PART,
  allocateNoteId,
  atomicNoteSpansOf,
  customMarkFollows,
  findNoteById,
  formatNoteScopeId,
  isContinuationSeparatorNode,
  isEndnotesNode,
  isFootnotesNode,
  isNormalNote,
  isNoteAtomNode,
  isNoteNode,
  isNoteRefNode,
  isNoteReferenceNode,
  isSeparatorNode,
  noteAtomText,
  noteIdOf,
  noteKindOf,
  noteRefKindOf,
  noteReferenceKindOf,
  noteTypeOf,
  notesOf,
  parseNoteId,
  parseNoteScopeId,
  type AtomicNoteSpan,
  type NoteKind,
  type NoteType,
} from './note-nodes.js';
export {
  DEFAULT_ENDNOTE_PROPERTIES,
  DEFAULT_FOOTNOTE_PROPERTIES,
  authoredDocumentEndnoteProperties,
  authoredDocumentFootnoteProperties,
  authoredEndnotePropertiesFromSectPr,
  authoredFootnotePropertiesFromSectPr,
  isLegalEndnotePosition,
  isLegalFootnotePosition,
  isLegalNumRestart,
  parseAuthoredNoteProperties,
  resolveEndnoteProperties,
  resolveFootnoteProperties,
  settingsPartOf,
  type AuthoredNoteProperties,
  type EndnotePosition,
  type FootnotePosition,
  type NoteNumRestart,
  type ResolvedEndnoteProperties,
  type ResolvedFootnoteProperties,
} from './note-properties.js';
export {
  MAX_NOTE_REFERENCE_SCAN,
  MAX_NOTE_REFERENCE_PARTS,
  collectNoteReferences,
  collectPackageNoteReferences,
  createNoteReferenceScanBudget,
  diagnoseNoteReferences,
  normalNoteIds,
  notesPartHasId,
  resolveNotesPart,
  type NoteDiagnostic,
  type NoteDiagnosticCode,
  type NoteReferenceHit,
  type NoteReferenceScanBudget,
} from './note-references.js';
export {
  applyNoteLifecycleOp,
  cascadeDeletedNoteReferences,
  isNoteLifecycleOp,
  type CascadeDeletedNoteReferencesOptions,
  type NoteLifecycleImpact,
  type NoteLifecycleOp,
  type NoteLifecycleOptions,
  type NoteLifecycleRejection,
  type NoteLifecycleResult,
} from './note-lifecycle.js';
export { cascadeEmptiedComments, deleteCommentThread, hasAnyComment } from './comment-lifecycle.js';
export {
  NO_TRACKING_SETTINGS,
  readTrackingSettings,
  type DocumentTrackingSettings,
} from './tracking-settings.js';
export {
  DEFAULT_VIEW_SETTINGS,
  readViewSettings,
  type DocumentViewSettings,
} from './view-settings.js';
export {
  CONTENT_CONTROL_ID_MAX,
  CONTENT_CONTROL_PROPERTY_ORDER,
  MAX_CONTENT_CONTROLS_PER_PART,
  MAX_CONTENT_CONTROL_NESTING,
  allocateContentControlId,
  contentControlContentChildren,
  contentControlContentNodeOf,
  contentControlEndPropertiesNodeOf,
  contentControlLevelOf,
  contentControlPropertiesNodeOf,
  contentControlPropertiesOf,
  contentControlTextOf,
  contentControlsIn,
  findContentControl,
  flattenContentControls,
  isContentControlContentNode,
  isContentControlNode,
  isContentControlWrapper,
  lockForbidsEdit,
  lockForbidsRemoval,
  orderedContentControlProperties,
  parseContentControlId,
  resolveContentControlLock,
  type ContentControlCheckbox,
  type ContentControlCheckboxState,
  type ContentControlDataBinding,
  type ContentControlDateFormat,
  type ContentControlEntry,
  type ContentControlKind,
  type ContentControlLevel,
  type ContentControlListItem,
  type ContentControlLock,
  type ContentControlProperties,
} from './content-control-nodes.js';
export {
  MAX_STORY_SDT_NESTING,
  bodyStoryRoot,
  collectStoryParagraphs,
  storyParagraphs,
  storyRootsOf,
  type OoxmlStoryKind,
  type OoxmlStoryRoot,
} from './story-blocks.js';
export {
  CUSTOM_XML_PROPS_REL,
  CUSTOM_XML_PROPS_TYPE,
  CUSTOM_XML_REL,
  DATASTORE_NAMESPACE_URI,
  customXmlDataParts,
  datastoreItemIdFor,
  findCustomXmlDataPart,
  withCustomXmlDataPart,
  withoutCustomXmlDataPart,
  type CustomXmlDataPart,
  type CustomXmlDataPartResult,
} from './custom-xml-part.js';
export {
  customXmlLabelXPath,
  customXmlNodes,
  customXmlPrefixMappings,
  readCustomXmlNode,
  withCustomXmlNode,
  withoutCustomXmlNode,
  withoutOrphanCustomXmlNodes,
  type CustomXmlNode,
} from './custom-xml-nodes.js';
export {
  CUSTOM_NODE_XPATH_PREFIX,
  boundCustomXmlNodeIdOf,
  boundCustomXmlNodeIds,
  boundCustomXmlNodeIdsInPackage,
  customNodeBinding,
  type CustomNodeBinding,
} from './custom-node-payloads.js';
export {
  withExportedCustomNodes,
  type CustomNodeExportPolicy,
  type CustomNodeExportRequest,
  type CustomNodeExportResult,
} from './custom-node-export.js';
